/**
 * @file CM_DrawNode.cpp
 * @author Christopher McCooey
 * @date February 17, 2020
 * @brief This data structure is used for an associative map data structure to connect the
 * the graphical user interface to the linked list data strucuture. Do not edit this file.
 */

#include "CM_DrawNode.h"

CM_DrawNode::CM_DrawNode()
    :cx(0), cy(0), index(-1), angle(0.0)
{
}
CM_DrawNode::CM_DrawNode(int cX, int cY, int idx, double Angle)
    :cx(cX), cy(cY), index(idx), angle(Angle)
{
}
CM_DrawNode::CM_DrawNode(const CM_DrawNode &other)
    :cx(other.cx), cy(other.cy), angle(other.angle)
{
}
CM_DrawNode &CM_DrawNode::operator=(const CM_DrawNode &other)
{
    cx = other.cx;
    cy = other.cy;
    index = other.index;
    angle = other.angle;
    return *this;
}
