/**
 * @file CM_DrawNode.h
 * @author Christopher McCooey
 * @date February 17, 2020
 * @brief This data structure is used for an associative map data structure to connect the
 * the graphical user interface to the linked list data strucuture. Do not edit this file.
 */

#ifndef CM_DRAWNODE_H
#define CM_DRAWNODE_H

struct CM_DrawNode
{
    int cx;
    int cy;
    int index;
    double angle;

    CM_DrawNode();
    CM_DrawNode(int cX, int cY, int idx, double Angle);
    CM_DrawNode(const CM_DrawNode &other);

    CM_DrawNode& operator=(const CM_DrawNode &other);
};

#endif // CM_DRAWNODE_H
