/**
 * @file CM_GraphicsView.h
 * @author Christopher McCooey
 * @date February 12, 2020
 * @brief This class represent the main graphical display port. This file is used to display the
 * circular linked list using radial geometry. Do not edit this file.
 */

#ifndef CM_GRAPHICSVIEW_H
#define CM_GRAPHICSVIEW_H

class DoublyLinkedList;
class CM_ListEntry;

#include <QWidget>
#include <QStringList>
#include <QString>

enum ModeEnum
{
    Mode_Normal = 0,
    Mode_Find_First,
    Mode_Find_Last,
    Mode_Finished,
    Mode_Total
};

class CM_GraphicsView : public QWidget
{
    Q_OBJECT
public:
    explicit CM_GraphicsView(QWidget *parent = nullptr);
    virtual ~CM_GraphicsView();

    void keyFunction(QKeyEvent* ev); //used to propagate keyboard events from parent window
    void setMode(ModeEnum mode);

protected:
    void keyReleaseEvent(QKeyEvent* ev);
    void resizeEvent(QResizeEvent* ev);
    void mousePressEvent(QMouseEvent* ev);
    void mouseMoveEvent(QMouseEvent* ev);
    void mouseReleaseEvent(QMouseEvent* ev);
    void paintEvent(QPaintEvent *ev);

signals:

public slots:
    void clearSlot();
    void randomStringSlot();

private:
    DoublyLinkedList* m_list;
    CM_ListEntry* m_entry;
    ModeEnum m_mode;
    QString m_helper_text;
    QStringList m_random_strings;
    int m_random_string_index;
    int m_found_location;
};

#endif // CM_GRAPHICSVIEW_H
